pyneuroml/pynml.py
Fixes #21.
I made the `pynml` command-line options as close to the `jnml` command-line options as possible.
The only option that I had troubles porting to `pynml` is `-neuron`, because `argparse` doesn't support nested options, so the usage/help message for `-neuron` is not as good as that for the rest of the options.
Also, for the usage/help messages of the added command-line options, I mostly used what was already in `jnml` and `pynml`. But if there are any changes to be made to these messages, now is probably a good time to do it.
=> Add all missing jnml options

pyneuroml/neuron/analysis/HHanalyse.py
Fixes failure when there are comments inside STATE defined in a mod file. Uses regular expressions now.
Also a verification of chanToTest from SUFFIX keyword and an error for when not a distributed mechanism - defined as per 9.2.1 The NEURON block in 'The Neuron Book', 2006
=> Fixes issue 47

pyneuroml/pynml.py
Print output of command during execution.
That change is pretty helpful for Sibernetic simulations.
=> Add execute_command_in_dir_with_realtime_output.

setup.py
Airspeed is now at 0.5.16, so it's good to just let it be grater than
0.5.5 (unless we need to be at the specific 0.5.4 version?)
https://pypi.org/project/airspeed/
=> Update airspeed requirement

pyneuroml/pynml.py
get_window_title and set_window_title have been deprecated in matplotlib
version 3.4 and will be dropped in future releases.
Reference: https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.4.0.html#backend-deprecations
Fixes #95
=> feat: update matplotlib usage to remove deprecated methods

pyneuroml/pynml.py
Follows the same logic as -neuron, but also includes an additional -np
flag for MPI runs that NetPyNE supports.
Fixes https://github.com/NeuroML/pyNeuroML/issues/80
=> enh(pynml): add -netpyne option

examples/Vm_plot.py, pyneuroml/analysis/ChannelDensityPlot.py, pyneuroml/analysis/ChannelHelper.py, pyneuroml/analysis/NML2ChannelAnalysis.py, pyneuroml/analysis/__init__.py, pyneuroml/lems/LEMSSimulation.py, pyneuroml/lems/__init__.py, pyneuroml/neuron/__init__.py, pyneuroml/neuron/mod/parse_mod_file.py, pyneuroml/plot/PlotSpikes.py, pyneuroml/povray/MakeMovie.py, pyneuroml/povray/NeuroML2ToPOVRay.py, pyneuroml/povray/OverlaySimulation.py, pyneuroml/pynml.py, pyneuroml/swc/ExportSWC.py, pyneuroml/tune/NeuroMLController.py, pyneuroml/tune/NeuroMLSimulation.py, pyneuroml/tune/NeuroMLTuner.py
We now use logger.info to display information to the user. The default logger level is also INFO, so all of these messages are displayed by default. Information that should not be shown to the user by default should use logger.debug.
=> Finish consolidating logging

test-ghactions.sh
=> test(modchananalysis): test to check that nrnivmodl is run when required

pyneuroml/analysis/__init__.py
To allow analysis of multi-compartmental cells with inputs at different locations
=> feat(generate-if-curve): allow specifying segment and fraction along

pyneuroml/analysis/__init__.py
Minor addition to the method to also just save the spike threshold current value to a file
=> feat(if-curve): save spike threshold current value also

pyneuroml/plot/PlotMorphology.py
Necessary for for matplotlib 3.8
Reference:
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#changes-of-api-after-deprecation
=> fix(plots): provide axis for colorbar

pyneuroml/plot/PlotMorphologyVispy.py
Otherwise this throws an error and the tool crashes
The change is near line 377. The other bits are pre-commit reformatting the file.
=> fix(vispy-morph): get title from cell object if no network is found

pyneuroml/plot/PlotMorphologyVispy.py
Some very minor tweaks to make the interactive schematic plots better. Now, they use the cell population colors if provided in the neuroml files, or users can choose from a single colour for the full cell, different colors for soma, axon, dendrites, or different colours for each unbranched segment group.
=> feat(morph-plots): improve colouring of cells/groups in schematic plot

pyneuroml/plot/PlotMorphologyVispy.py, tests/plot/test_morphology_plot.py
Adapted from https://github.com/vispy/vispy/blob/main/vispy/geometry/generation.py#L451
I don't notice a performance hit, but it'll be good to test this out more just to be sure.
=> Close cylindrical meshes for vispy viewer

pyneuroml/analysis/__init__.py, pyneuroml/pynml.py
Note: remove these functions from pynml in the future
See also: https://github.com/suny-downstate-medical-center/netpyne/pull/787
=> feat(pynml): do not import plotters if mpl is not already imported

pyneuroml/plot/Plot.py, pyneuroml/plot/PlotSpikes.py
This enables users to override the rcparams directly to tweak graphs, which is very useful.
https://matplotlib.org/stable/users/explain/customizing.html
=> feat(plotter): use matplotlib rcparams defaults for missing options

pyneuroml/nsgr/__init__.py
For NEURON simulations, we only need the generated NEURON files, but for NetPyNE, some bits are generated (channel mod files, for example), but others are directly imported (networks/cells). So we need to ensure that all of these files are also available to the main NetPyNE script.
=> fix(nsgr-netpyne): include model files in NSG zip also

.github/workflows/ci.yml
Requires a new release of neurotune.
=> Drop explicit inspyred installation in CI

pyneuroml/plot/PlotMorphologyVispy.py
During refactoring, we'd used only the one radii, but that meant we only got cylinders, not cones and other related shapes where the two radii can be different.
Note that this means there may be more unique meshes, and so, the precision may be reduced more by the heuristic. But, it will allow users with more computing power to get more accurate meshes.
=> fix(vispy): use proximal and distal radii for mesh

setup.cfg
Use qt6 by default, but allow users to install the qt5 version too. This is just to support systems that may not use qt6 yet.
=> feat: split vispy into qt5 and qt6 deps

.pre-commit-config.yaml, pyneuroml/annotations.py
These work better with LEMS, since we need to define the LEMS component  types completely
=> More annotation tweaks: remove unused ids, use `rdf:li` 

pyneuroml/utils/__init__.py
Adds an option to allow users to rotate cell without creating a copy. 
@lej0hn : can do this in the translate function too, so that if the two operations are run one after the other, we don't need to create a copy each time.
=> feat(rotation): allow users to pick if they want a copy

pyneuroml/plot/PlotMorphology.py, pyneuroml/plot/PlotMorphologyVispy.py, pyneuroml/utils/__init__.py, pyneuroml/utils/plot.py, tests/plot/L23-example/HL23VIP.morph.cell.nml, tests/plot/test_morphology_plot.py
=> Support visualisation of morphology only files

pyneuroml/biosimulations.py
Small tweak so that I can fetch results from models ran remotely on biosimulators.
=> add downloads URL as biosimulations.submit_simulation_archive return value

pyneuroml/plot/PlotMorphologyVispy.py
Move the calculations for constant plot types to the cells, and make soma thicker to make it easy to see.
The mesh creator is now much more specific and does not need to know what type of plot it's working on. It simply takes a list and spits out a mesh.
=> feat(vispy): simplify mesh creation

pyneuroml/lems/LEMSSimulation.py, pyneuroml/lems/__init__.py
this also removes the need for overriding `__setattr__` etc. 
This not a breaking change because `LEMSSimulation.lems_info` is still available (as a property).
=> Refactor LEMSSimulation to remove the need of an explicit dict (just use `vars(self)` instead
