pyneuroml/pynml.py
=> small option

pyneuroml/neuron/analysis/HHanalyse.py
FROM 0 TO 1 must be excluded. Sorry about that.
<One day I will write tests>
=> error in my previous fix

pyneuroml/lems/__init__.py
Enables to save spikes from only a subset of neurons.
=> Spike saving updated

pyneuroml/pynml.py
Otherwise, it crashes and gives a trace.
Also adds a short usage snippet.
=> [pynml-summary] check for arguments

pyneuroml/pynml.py
=> doc: document usage of generate_plots utility function

pyneuroml/pynml.py
This tweaks the command line argument parsing to allow us to take
multiple NML/LEMS files as input in the shared options. For all the
options that can be applied to these, we then iterate over the file
list.
A few options don't use the file list given at all, so we handle them
separately.
=> enh: allow pynml to process multiple files

docs/source/pyneuroml.analysis.rst, docs/source/pyneuroml.lems.rst, docs/source/pyneuroml.plot.rst, docs/source/pyneuroml.povray.rst, docs/source/pyneuroml.rst, docs/source/pyneuroml.swc.rst, docs/source/pyneuroml.tune.rst
Doesn't touch code, only docs Just testing RTD CI,
=> docs: reorder sections to improve readability

README.md, pyneuroml/povray/NeuroML2ToPOVRay.py, pyneuroml/pynml.py, pyneuroml/tune/NeuroMLController.py, pyneuroml/tune/NeuroMLSimulation.py, pyneuroml/tune/NeuroMLTuner.py, requirements-dev.txt, setup.py
@pgleeson: I couldnt think of another way of working around lxml.etree not being pickled here. Does this look OK?
I'll try to add more tests to check the tuning code, maybe a stripped down version of the example we're doing for docs.
=> Tweaks to tuner code

pyneuroml/pynml.py, tests/test_pynml.py
- Also, printing stderr output from jnml command
=> Specifying universal_newlines so "realtime output" works correctly

docs/requirements.txt, docs/source/pyneuroml.neuron.rst, docs/source/pyneuroml.rst, pyneuroml/neuron/__init__.py, pyneuroml/neuron/nrn_export_utils.py
So that the API docs have information on them.
=> Document neuron export functions

pyneuroml/utils/__init__.py, tests/utils/test_utils.py
Depends on https://github.com/NeuralEnsemble/libNeuroML/pull/140
=> feat(utils): validate component on creation by factory

setup.py
also ensures that `pip install ..[all]` works
=> feat: improve installation of extra deps

pyneuroml/pynml.py
=> Adding logic for one-shot validation of multiple input files

pyneuroml/neuron/analysis/HHanalyse.py
=> pynml-modchananalysis excepting on division by zero

pyneuroml/pynml.py
=> feat(pynml): include more info in version

setup.cfg
It doesn't seem to be imported in the code at all. Let's see if CI passes.
=> chore(deps): remove unused pandas

pyneuroml/plot/PlotMorphology.py, pyneuroml/plot/PlotMorphologyVispy.py, pyneuroml/utils/__init__.py, pyneuroml/utils/plot.py, setup.cfg, tests/plot/test_morphology_plot.py
Includes some heuristics to decide which cylinders are considered instances of the same mesh---could be further tweaked.
=> Improve performance of vispy plotter using meshes and their instances

pyneuroml/pynml.py
So that it can be used via pyneuroml without requiring users to figure out how to use it through neuromllite
=> feat(graph-generator): allow passing kwargs to GraphVizHandler

pyneuroml/lems/LEMSSimulation.py, pyneuroml/lems/LEMS_TEMPLATE.xml, tests/lems/test_lemssimulation.py
So that folks can actually use this new feature we've added.
=> Expose `meta` in LEMSSimulation

pyneuroml/plot/PlotMorphology.py, pyneuroml/plot/PlotMorphologyVispy.py
For ex: 
Useful to mark what segments are being used/recorded from.
Done in vispy, need to do in matplotlib viewer also.
=> feat: morphology plotting: allow marking/highlighting individual segments

pyneuroml/lems/LEMSSimulation.py
It's more in line with the rest of NeuroML where we provide values as strings with units.
Fixes #199
=> feat(LEMSSimulation): allow using float/str for duration/dt

.github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml, setup.cfg
https://github.com/astral-sh/ruff
=> chore: move to ruff

pyneuroml/annotations.py, tests/test_annotations.py
Also improves handling of authors/contributors
=> feat(annotations): improve for use as embedded annotations

pyneuroml/analysis/NML2ChannelAnalysis.py
Also add an error to inform user if no channels were obtained from channel file.
=> fix(nml-channel-analysis): include `ionChannelVShift`

pyneuroml/analysis/NML2ChannelAnalysis.py, pyneuroml/neuron/analysis/HHanalyse.py, pyneuroml/utils/__init__.py
To ensure that the graphs from modchananalysis and pynml-chananalysis are identical.
=> feat(pynml-modchananalysis): add labels and fix file name

pyneuroml/utils/__init__.py, tests/utils/test_utils.py
Aims to solve #360 . Function translates cell so that its soma at the origin of the axes
=> Added translate_cell function

pyneuroml/__init__.py, pyneuroml/analysis/ChannelDensityPlot.py, pyneuroml/analysis/NML2ChannelAnalysis.py, pyneuroml/biosimulations.py, pyneuroml/neuron/__init__.py, pyneuroml/plot/PlotMorphology.py, pyneuroml/plot/PlotMorphologyVispy.py, pyneuroml/povray/NeuroML2ToPOVRay.py, pyneuroml/tune/NeuroMLTuner.py, pyneuroml/utils/plot.py, pyneuroml/xppaut/__init__.py
some fixes to linter issues that ruff flagged
ready to merge once all tests pass
=> chore: linter fixes

pyneuroml/annotations.py, tests/test_annotations.py
Also adds the docstring to the wrapper function to aid users.
=> Add `bqbiol.is`

.github/workflows/ci.yml
Reference:
https://github.com/marocchino/sticky-pull-request-comment/issues/930#issuecomment-1515431005
=> ci: update comment bit to also work on PRs from forks

.github/workflows/ci.yml
Sometimes fails on GHA without the quotes.
=> ci: tweak pip command
